Add support for Deepseek V2
huggingface/text-generation-inference pull request #2224
Opened 2024-07-12 11:00 UTC by danieldk

# What does this PR do?

Deepseek V2 is a MoE model from Deepseek. Relevant variations compared to other models:

- Grouped top-K in expert selection.
- mscale in yarn is calculated using the `mscale` and `mscale_all_dim` configuration options.
- `mscale_all_dim` is also used in scaling attention softmax.
- Permuting of the query/key representations before applying rotary embeddings.
- Some projections cannot be sharded (`q_a_proj`, `kv_a_proj_with_mqa`). So, we need weight loads that supports quantized weights. To this end `{Weights,WeightsLoader}.get_weight` was added.
- The query/key head dimensionality differs from that of the value, so we need to pad during attention.
- Heads with size 192, needs an extension to our paged attention fork and we need to ensure that the KV cache is allocated with the correct size.
- Shared experts.

TODO before this can move away from draft:

- [ ] Get https://github.com/Narsil/vllm/pull/2 merged for support for head size 192.
- [ ] Update our vllm git SHA to pull the version with the support for head size 192 merged.
- [ ] Run release tests to ensure that the additions to the `Weights`/`WeightsLoader` and yarn rotary embeddings didn't break anything.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2024-07-18 16:07 UTC, drbh requested changes
looks great just a couple small syntax comments

2024-07-19 08:55 UTC, danieldk commented on server/Makefile-vllm
> +	cd vllm  && git fetch origin pull/2/head:pr-2 && git checkout $(commit_cuda) && pip install -e .
Ah cool, I didn't see that. Updated.

2024-07-19 08:55 UTC, danieldk commented on server/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py
> +        )
Fixed.

2024-07-19 08:56 UTC, danieldk commented on server/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py
> +        self.softmax_scale = self.softmax_scale * mscale * mscale
Moved the import to the top of the file, put the softmax scale calculation in a single line.

2024-07-19 08:56 UTC, danieldk commented on server/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py
> +            )
Done.

2024-07-19 08:56 UTC, danieldk commented on server/text_generation_server/models/custom_modeling/flash_deepseek_v2_modeling.py
> +        # out = self.moe_infer_cpu(x, topk_ids, topk_weights) * self.routed_scaling_factor
Removed.

2024-07-19 15:13 UTC, drbh approved these changes
lgtm!

2024-07-19 15:23 UTC, merged